### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by GuillaumeLachaud** [aandrewww/pino-sentry#1]
Hi!

Most Pino transports offer both CLI and API usages. Looking at the documentation, it looks like this one only allows CLI usage ?

**Comment by GuillaumeLachaud** [comment]
Looks like the PinoSentryTransport.createWriteStream is not exported for use. Any chance we can have it exported ?

Thanks!

**Comment by aandrewww** [comment]
I added API support.
Please check https://github.com/aandrewww/pino-sentry#api

**Comment by GuillaumeLachaud** [comment]
Thanks!
