### ISSUE TITLE
Local Scope

### ISSUE THREAD

**Issue by on2air** [aandrewww/pino-sentry#13]
Looks like if there is a tags object passed to a log entry, it will get set to the global scope using `Sentry.configureScope`

shouldn't that be a local scoping specific to that message only using `Sentry.withScope`

see: https://docs.sentry.io/enriching-error-data/scopes/?platform=javascript#local-scopes

**Comment by on2air** [comment]
@aandrewww - any thoughts on changing the scope?

**Comment by aandrewww** [comment]
Yes, seems that withScope (local scope) is the right way.
I'll fix it.

**Comment by glensc** [comment]
https://github.com/aandrewww/pino-sentry/pull/29 @on2air can you validate the change being correct?

**Comment by aandrewww** [comment]
@on2air fix it. thanks @glensc 
try to check please
