### ISSUE TITLE
Ignore non-json lines

### ISSUE THREAD

**Issue by eauc** [aandrewww/pino-sentry#14]
Hello,

I'm under the impression that currently the process crashes and stop processing logs when it encounters a non JSON.parse-able line.
Which, if true, makes it hard to use in production where I don't want to lose sentry and my stdout if someone forgets a console.log (or a librairie prints something on its own)
Would it be possible to add an option to silently ignore non-JSON lines ?
I could filter-out those lines in the pipe chain but it means I lose them in the final stdout too.

Any idea ?
Thanks in advance

**Comment by aandrewww** [comment]
It's a good idea. 
I'll think about it and do it something with it :)
