### ISSUE TITLE
How to only send errors to sentry?

### ISSUE THREAD

**Issue by gr2m** [aandrewww/pino-sentry#15]
Apologies if I am missing something obvious 🙏🏼 

As far as I can tell, when I use `pino-sentry` like this `node my-app.js | pino-sentry` then _everything_ is sent to Sentry, either as exception, or using `Sentry.captureMessage`:

https://github.com/aandrewww/pino-sentry/blob/3c1625349d8ac513232db4d009e1d00d57a6a0e4/src/transport.ts#L105-L111

But the way I use Sentry is to only use it for tracking exceptions. Is there a way to configure `pino-sentry` that way?

**Comment by gr2m** [comment]
If anyone is interested, I created a fork that does exactly that: https://github.com/gr2m/pino-sentry-errors/

But I still think an option in `pino-sentry` would be the better solution

**Comment by gabemeola** [comment]
@gr2m I referred to some of your logic and created a PR to update this project 😀 https://github.com/aandrewww/pino-sentry/pull/17

**Comment by gr2m** [comment]
Awesome 👏 did you by chance also figure out https://github.com/aandrewww/pino-sentry/issues/16?

**Comment by aandrewww** [comment]
Hey, guys.
Thanks for the issue and PR.
I completely agree with all.
PR merged
+ pino-sentry@0.4.0
