### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by gr2m** [aandrewww/pino-sentry#16]
I see this error message when I pipe my `pino` output into `pino-sentry`

```
Cannot read property 'on' of undefined
TypeError: Cannot read property 'end' of undefined
    at onend (_stream_readable.js:681:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

The simplest test case I could come up with is a `test.js` file:

```js
// test.js
require('pino')().info('test')
```

and then running piping it into `pino-sentry`

```
$ node test.js | node dist/cli.js --dsn=https://123@123.ingest.sentry.io/123
start
Cannot read property 'on' of undefined
TypeError: Cannot read property 'end' of undefined
    at onend (_stream_readable.js:681:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Any idea what this could mean? The error message is not very helpful :(

**Comment by aandrewww** [comment]
Yes, I see the same problem.
I'm gonna research and fix it ASAP

**Comment by gabemeola** [comment]
Was able to figure this out. Looks like `.pipe` was the culprit here.

**Comment by aandrewww** [comment]
@gabemeola Wow. Nice. Could you make a PR? It will be great)

**Comment by aandrewww** [comment]
@gabemeola Sorry... Already made)
I'm checking ...
