### ISSUE TITLE
Update Sentry SDK to 6.*

### ISSUE THREAD

**Issue by vladshcherbin** [aandrewww/pino-sentry#24]
Hey 👋 

Current sentry SDK version is 5.\*, would be nice to test if 6.\* is compatible ([SDK changelog](https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#600) says no breaking changes) and update SDK if possible.

Sentry displays this recommendation:

![image](https://user-images.githubusercontent.com/6711845/114281202-b67d0680-9a45-11eb-895d-d0bd1adce2c8.png)

Thanks

**Comment by aandrewww** [comment]
Updated :)
pino-sentry@0.7.0
