### ISSUE TITLE
Attempted import error: 'extractNodeRequestData' is not exported from '@sentry/util'.

### ISSUE THREAD

**Issue by djaax** [aandrewww/pino-sentry#27]
I'm trying to get `pino-sentry` working but importing like

```
import { createWriteStream } from 'pino-sentry';
```

throws the following error:

```
node_modules/@sentry/node/node_modules/@sentry/tracing/esm/hubextensions.js
Attempted import error: 'extractNodeRequestData' is not exported from '@sentry/util'.
```

Any ideas?

**Comment by glensc** [comment]
1. node version?
2. typescript or plain javascript?

**Comment by glensc** [comment]
@aandrewww I think this can be closed. not reproducible and the user probably already solved it.
