### ISSUE TITLE
Publish Git tags

### ISSUE THREAD

**Issue by glensc** [aandrewww/pino-sentry#31]
There are no releases or tags in GitHub:
- https://github.com/aandrewww/pino-sentry/releases
- https://github.com/aandrewww/pino-sentry/tags

please publish the historic tags.

if needed, I can try to figure out where each tag might have landed from commit history.

**Comment by glensc** [comment]
cc @aandrewww

**Comment by aandrewww** [comment]
@glensc Hi.
I published npm packages without any git tags and github releases.
Is it problem ?

**Comment by glensc** [comment]
@aandrewww this is the issue me asking you to create and push git tags as well.

if you need help on this, I can help, you need to ask

**Comment by aandrewww** [comment]
Done!
Created tags and releases.
@glensc
