### ISSUE TITLE
Q: Any plan to migrato to v7+ transport?

### ISSUE THREAD

**Issue by rodmoreno** [aandrewww/pino-sentry#33]
Recently I read about new [v7+ transports ](https://getpino.io/#/docs/transports?id=v7-transports)and I would like to know if you have any plan to support this new architecture?

**Comment by glensc** [comment]
Does pino 7.x support 6.x transports? or they are mutually exclusive?

**Comment by glensc** [comment]
> Does pino 7.x support 6.x transports? or they are mutually exclusive?

I've done local testing, and seems 0.11 can work with pino 7.x.

how to outline this better in this project, in readme? as pino not even included in dependencies, i.e to be installed via peerDependencies?
- https://github.com/aandrewww/pino-sentry/blob/0.11.0/package.json#L37-L43

**Comment by rasmuslp** [comment]
> how to outline this better in this project, in readme? as pino not even included in dependencies, i.e to be installed via peerDependencies?

If you use peerDependencies, not that there is different behaviour depending on the version of NPM. I came across that when upgrading my eslint config to the latest airbnb.

With that said, peerDependencies sounds like what you would want to use for 'plugins', as they refer to it in the `package.json` documentation here: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies

For some inspiration, you can see how they communicate dealing with peerDependencies here: https://www.npmjs.com/package/eslint-config-airbnb
And how I did here: https://github.com/rasmuslp/eslint-config-rasmuslp

**Comment by meotimdihia** [comment]
@glensc Does it really work with Pino 7?
I am getting this error by a simple example:

```js
import pino from "pino"

async function main() {
  const transport = pino.transport({
    targets: [
      {
        target: "pino-sentry",
        options: {
          dsn: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        },
        level: "error"
      }
    ],
  })
  const logger = pino(
    transport
  )
  logger.error('test')
}
main()
  .catch(async e => {
    console.error(e)
  })

```

```
node dist/src/examples/test3.js
events.js:377
      throw er; // Unhandled 'error' event
      ^

TypeError: fn is not a function
    at C:\sources\a-cli\node_modules\pino\lib\worker.js:26:26
    at async Promise.all (index 0)
    at async module.exports (C:\sources\a-cli\node_modules\pino\lib\worker.js:13:13)        
    at async start (C:\sources\a-cli\node_modules\thread-stream\lib\worker.js:57:17)        
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:579:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:403:9)       
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
    ```

**Comment by glensc** [comment]
@meotimdihia I'm not using v7 api, then it works

the code is part of other framework, so some bits may be off
```ts
import { createWriteStream as createSentryStream } from "pino-sentry/dist/transport";
import { Level, Logger as BaseLogger, pino } from "pino";

const streams = [];
const sentryStream =  createSentryStream(sentryOptions);
streams.push({
        stream: sentryStream as any,
        level: (options.levels?.sentry || "error") as Level,
        name: "sentry",
});

const logger = pino(
  {
    level,
  },
  pino.multistream(streams),
);
```

See also this discussion:
- https://github.com/pinojs/pino-multi-stream/pull/76

**Comment by meotimdihia** [comment]
The same error is happening with the code:  (node.js 14)

```node
import pino from "pino"
import { createWriteStream as createSentryStream } from "pino-sentry/dist/transport"

const streams = []
const sentryStream = createSentryStream({
  dsn: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,
})
streams.push({
  stream: sentryStream,
})

logger = pino(
  {
    level: 'debug'
  },
  pino.multistream(streams)
)

export default logger
```

**Comment by glensc** [comment]
@meotimdihia the [exact code](https://github.com/aandrewww/pino-sentry/issues/33#issuecomment-1107458237) (after fixing the unterminated dsn string) produces no output for me, so no error.

your [previous code](https://github.com/aandrewww/pino-sentry/issues/33#issuecomment-1107356505) I get "the worker has exited" error

```
node_modules/thread-stream/index.js:281
      throw new Error('the worker has exited')
      ^

Error: the worker has exited
    at ThreadStream.flushSync (node_modules/thread-stream/index.js:281:13)
    at process.onExit (node_modules/pino/lib/transport.js:65:12)
    at process.emit (events.js:412:35)
    at process.emit (domain.js:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at process.exit (internal/process/per_thread.js:179:15)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (node_modules/@cspotcode/source-map-support/source-map-support.js:618:17)
    at process._fatalException (internal/process/execution.js:167:25)

```

pino@7.8.0, pino-sentry@0.11.0, pino-multi-stream@6.0.0

**Comment by glensc** [comment]
perhaps the node version is relevant?

**Comment by glensc** [comment]
@aandrewww perhaps close this one (and lock), as it's mixed content and therefore confusing for the reader. it started as a question, but then some user hijacked the issue with their bug report instead of creating their own issue and then disappeared as well.

**Comment by aandrewww** [comment]
@glensc @segevfiner agree with you

close
