### ISSUE TITLE
Automate npm publishing with GitHub Actions

### ISSUE THREAD

**Issue by glensc** [aandrewww/pino-sentry#44]
Are you interested carrying this to this repo:
- https://github.com/orta/danger-plugin-yarn/pull/51

asking because super negative feedback in some other repo where I did all the goodies but it was just rejected with lame reason.

**Comment by glensc** [comment]
@aandrewww shall I create PR then?

**Comment by glensc** [comment]
@aandrewww close t his issue if you've created the Automation type token and setup to this project.

**Comment by aandrewww** [comment]
done

**Comment by glensc** [comment]
alright, pushed 0.12.0 tag!

**Comment by glensc** [comment]
Published!
- https://www.npmjs.com/package/pino-sentry/v/0.12.0

ps: my npm username is [glen](https://www.npmjs.com/~glen), maybe add as Collaborator there too?
