### ISSUE TITLE
[Question]: is there any way to keep printing logs while also sent them to Sentry ?

### ISSUE THREAD

**Issue by Sefrancois** [aandrewww/pino-sentry#54]
Hello,

Is there a way to keep printing logs in standard output while they are also sent to Sentry ?

I'm asking this because if there is any issue on Sentry, we wouldn't see our logs anymore which would be a problem.

Thanks in advance,

Sebastien

**Comment by glensc** [comment]
this should be directed to pino, try searching pino multiple transports. pino 7+ made official way to have more than one transport.
